# Generated by Django 3.0.10 on 2021-05-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210526_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlocations',
            options={'ordering': ('num',), 'verbose_name': 'Location'},
        ),
    ]
