# Generated by Django 3.0.10 on 2021-05-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210526_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlocations',
            options={'ordering': ('-id',), 'verbose_name': 'Location'},
        ),
    ]
