# Generated by Django 3.0.10 on 2021-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210526_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlocations',
            options={'ordering': ('-num',), 'verbose_name': 'Location'},
        ),
        migrations.RemoveField(
            model_name='addlocations',
            name='hint',
        ),
    ]
