# Generated by Django 3.0.10 on 2021-05-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210527_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlocations',
            options={'ordering': ('-id',), 'verbose_name': 'Location'},
        ),
        migrations.AlterField(
            model_name='addlocations',
            name='photo',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
    ]
